name: Update Data Every 24 Hours

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch:  # Manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run fetch action network script
        run: |
          export API_KEY="${{ secrets.API_KEY }}"
          export FORM_ID="${{ secrets.FORM_ID }}"
          node fetch_action_network.js

      - name: Commit and push updated data.json
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add data.json
          git commit -m "Update data.json with new Action Network data"
          git push https://${{ secrets.ACTIONS_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
